# Permalinks
permalink:           pretty

# Setup
title:               Morphology
tagline:             welcome!
url:                 http://blog.morp.holo.gy
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Hayden
  url:               https://github.com/Morphology-domain
  email:             webmaster+blog@morp.holo.gy

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Morphology-domain/blog-morphology
google_analytics:
  #id:                

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
